update

diff --git a/docker/build/Dockerfile b/docker/build/Dockerfile
--- a/docker/build/Dockerfile
+++ b/docker/build/Dockerfile
@@ -4,20 +4,22 @@ WORKDIR /var/www/html
 
 USER root
 
-#COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
+RUN apk add --no-cache nodejs npm
 
 COPY . .
 
 RUN composer install --no-interaction --prefer-dist
 
-#COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
+RUN npm install
+
+RUN npm run build
 
 RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html/storage /var/www/html/bootstrap/cache
 
-#RUN mkdir -p /var/log/nginx && chown -R www-data:www-data /var/log/nginx
+# EXPOSE 80
 
-#EXPOSE 80
+CMD nginx -g "daemon off;" & php-fpm -F
 
-#CMD nginx -g "daemon off;" & php-fpm -F
+# HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl --silent --fail http://localhost/ || exit 1
 
-#HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl --silent --fail http://localhost/ || exit 1
+USER www-data
